#include<iostream>
#include<map>
#include<vector>
using namespace std;

int main(){
	vector<string> s{"SATO","SUZUKI","TAKAHASHI","TANAKA","WATANABE","ITO","YAMAMOTO","NAKAMURA","KOBAYASHI","KATO",
"YOSHIDA","KOYANAGI","SASAKI","YAMAGUCHI","MATSUMOTO","INOUE","SAITO","KIMURA","HAYASHI","SHIMIZU",
"IKEDA","ABE","MORI","HASHIMOTO","YAMASHITA","ISHIKAWA","NAKAJIMA","MAEDA","FUJITA","OGAWA",
"OKADA","GOTO","HASEGAWA","MURAKAMI","KONDO","ISHII","SAKAMOTO","ENDO","AOKI","NISHIMURA",
"FUKUDA","MIURA","FUJIWARA","MATSUDA","OKAMOTO","NAKAGAWA","HARADA","TAKEUCHI","TAMURA","KANEKO",
"NAKAYAMA","ISHIDA","UEDA","NAKANO","MORITA","SHIBATA","YOKOYAMA","KUDO","MIYAZAKI","TAKADA",
"ANDO","SAKAI","TAKAGI","KAWAMOTO","KOJIMA","MURATA","TAKEDA","UENO","SUGIYAMA","MASUDA",
"SUGAWARA","HIRANO","KOYAMA","KUBO","CHIBA","MATSUI","IWASAKI","NOGUCHI","MATSUO","KINOSHITA",
"KIKUCHI","NOMURA","SANO","WATABE","ARAI","SUGIMOTO","SAKURAI","FURUKAWA","ICHIKAWA","SHIMADA",
"KOMATSU","TAKANO","MIZUNO","YOSHIKAWA","YAMAUCHI","NISHIDA","KIKUCHI","KITAMURA","HAMADA","IGARASHI",
"YASUDA","KAWAGUCHI","HIRATA","KAWASAKI","AZUMA","HONDA","KUBOTA","YOSHIMURA","TSUJI","NAKANISHI",
"FUKUSHIMA","IWATA","HATORI","HIGUCHI","MATSUOKA","YAMANAKA","NAGAI","TAGUCHI","AKIYAMA","TSUCHIYA",
"ISHIHARA","MATSUSHITA","BABA","YOSHIOKA","KOIKE","ASANO","NODA","KAWAMURA","HIROSE","HOSHINO",
"KURODA","OZAKI","TANABE","NAGATA","HORI","SUGANO","NISHIYAMA","KATAYAMA","HIRAI","SAWADA",
"HONMA","HAYAKAWA","YOKOTA","ARAI","OKAZAKI","KAMATA","NARITA","MIYATA","ODA","SUDO",
"SHINOHARA","KURIHARA","MIYAKE","OZAWA","FUKUI","UMEMOTO","MINAMI","OKUMURA","KATAOKA","UCHIYAMA",
"KUWAHARA","OKA","TOMITA","SEKIGUCHI","MATSUNAGA","OKUDA","KITAGAWA","MITANI","KOGA","UEHARA",
"YAGI","YOSHINO","SHIRAISHI","IMAMURA","KAMIMURA","KOIZUMI","NAKAO","NANBA","AOYAMA","HIRAYAMA",
"MAKINO","TERADA","SHIBUYA","SAKAGUCHI","KAWAI","ADACHI","YAMADA","AMANO","NISHI","OGURA",
"SUGIURA","KAKUTA","MIZUTANI","NEMOTO","TSUJIMOTO","SEKINE","MORISHITA","SAKUMA","TSUKAMOTO","UEDA",
"HORIUCHI","INAGAKI","NAKATANI","TANI","MATSUZAKI","HOSOKAWA","ENOMOTO","OKABE","NISHIO","HATAKEYAMA",
"TASHIRO","NAKAHARA","TSUDA","KUROKI","NAGAO","KANAI","SAEKI","NISHIOKA","HOSHI","YONEDA",
"TSUTSUMI","NOZAKI","OCHIAI","IZUMI","MACHIDA","YAMAZAKI","SUGITA","TOKUNAGA","KASAHARA","TAKIZAWA",
"MIKI","KAJIWARA","SUDA","HIDAKA","MURAI","HIROTA","HORIE","FUJISAWA","KAWABATA","IGUCHI",
"MUKAI","TAKENAKA","SAKAKIHARA","YASUI","TSUKADA","YANAGISAWA","OGATA","KURITA","UNO","KUBOTA",
"KAMEI","MOGI","MIWA","TAKAI","YAMAMURA","FURUTANI","NAGASHIMA","YOSHIZAWA","AOYAGI","SHINOZAKI",
"DEGUCHI","OGINO","KOMORI","ODAIRA","TAKASE","INADA","SONODA","YOKOI","TOMINAGA","TAKAMATSU",
"KANESHIRO","KOCHI","YANAGIDA","HORIKAWA","TANIMOTO","NINOMIYA","IKEGAMI","HIGA","HANADA","USUI",
"KATAGIRI","SUGIHARA","ARAYA","KAWARA","SENDA","YASHIMA","FUKUHARA","AIZAWA","KURATA","TABATA",
"MATSUSE","IWASE","TAGAMI","MORIOKA","NAKAMOTO","HORIGUCHI","KITAJIMA","TOKUDA","KASHIWAGI","AKASE"};
	
	map<char,int> mp;
	
	for(int i=0;i<s.size();i++){
		for(int j=0;j<s[i].size();j++){
			mp[s[i][j]]++;
		}
	}
	
	char ans;
	int anss=0;
	for(auto &el:mp){
		//cout<<el.first<<" "<<el.second<<endl;
		if(anss<el.second){
			anss=el.second;
			ans=el.first;
		}
	}
	
	cout<<ans<<endl;
	
	return 0;
}